[package]
name = "ahmoin/character-animate"
version = "0.0.7"
license = "MIT"
description = "https://github.com/ahmoin/character_animate"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "ahmoin/signal@0.1.0"
